packages = [
    "pydantic", 
    "pyyaml", 
    "jinja2", 
    "networkx", 
    "rich", 
    "typer", 
    "micropip",
    "jsonschema",
    "httpx",
    "python-dotenv",
    "graphviz",
    "shellingham"
]

[[fetch]]
files = ["./shellthreatmodel-0.1.0-py3-none-any.whl"]
